In [1]:
import pandas as pd

In [2]:
df_red = pd.read_csv('Red_Weather.csv')
df_rose = pd.read_csv('Rose_Weather.csv')
df_sparkling = pd.read_csv('Sparkling_Weather.csv')
df_white = pd.read_csv('White_Weather.csv')

In [3]:
df_red['type'] = 'Red'
df_rose['type'] = 'Rose'
df_sparkling['type'] = 'Sparkling'
df_white['type'] = 'White'

In [4]:
df_red.drop(columns=['city', 'country'], inplace=True)

In [5]:
wine_df = pd.concat([df_red, df_rose, df_sparkling, df_white], axis=0, ignore_index=True)
wine_df

,Name,Country,Region,Winery,Rating,NumberOfRatings,Price,Year,lat,lng,...,Nov_prcp,Nov_tsun,Dec_tavg,Dec_tmin,Dec_tmax,Dec_prcp,Dec_tsun,type,city,country
0,Pomerol 2011,France,Pomerol,Château La Providence,4.2,100,95.00,2011,44.931123,-0.199990,...,3.606667,16310.877930,3.770352,0.545016,7.278887,2.512903,18816.488281,Red,NaN,NaN
1,Lirac 2017,France,Lirac,Château Mont-Redon,4.3,100,15.50,2017,44.037200,4.691360,...,4.493333,23639.103516,6.816054,2.744145,12.079628,0.961290,25410.091797,Red,NaN,NaN
2,Erta e China Rosso di Toscana 2015,Italy,Toscana,Renzo Masi,3.9,100,7.45,2015,43.458654,11.138920,...,6.703333,16427.396484,7.227470,3.667322,11.165709,1.958065,22149.550781,Red,NaN,NaN
3,Bardolino 2019,Italy,Bardolino,Cavalchina,3.5,100,8.72,2019,45.547559,10.724215,...,2.990000,18802.570312,5.414707,2.268403,8.408726,0.754839,22706.322266,Red,NaN,NaN
4,Ried Scheibner Pinot Noir 2016,Austria,Carnuntum,Markowitsch,3.9,100,29.15,2016,48.114148,16.865783,...,0.703333,21962.705078,3.554911,1.230113,6.362371,0.325806,15976.619141,Red,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13085,Private Bin Sauvignon Blanc 2019,New Zealand,Marlborough,Villa Maria,4.1,4082,10.60,2019,-41.474475,173.833026,...,6.756667,36561.121094,16.466511,12.336403,21.633179,4.058064,38551.261719,White,Marlborough,New Zealand
13086,Blanco (Verdejo) 2018,Spain,Rueda,Marqués de Riscal,3.7,4155,6.30,2018,41.412979,-4.959753,...,0.740000,27725.917969,4.169382,0.314274,8.949759,1.112903,18953.107422,White,Rueda,Spain
13087,Sauvignon Blanc 2019,New Zealand,Marlborough,Oyster Bay,4.0,4423,10.66,2019,-41.474475,173.833026,...,6.756667,36561.121094,16.466511,12.336403,21.633179,4.058064,38551.261719,White,Marlborough,New Zealand
13088,Sauvignon Blanc 2018,New Zealand,Marlborough,Kim Crawford,3.9,5105,14.90,2018,-41.474475,173.833026,...,0.436667,37763.203125,18.173969,12.646081,24.600918,1.719355,44898.128906,White,Marlborough,New Zealand
13089,Sauvignon Blanc 2019,New Zealand,Marlborough,Hans Greyl,4.2,5817,7.75,2019,-41.474475,173.833026,...,6.756667,36561.121094,16.466511,12.336403,21.633179,4.058064,38551.261719,White,Marlborough,New Zealand

In [6]:
#Let's standardize the column names
wine_df.columns = wine_df.columns.str.lower()
wine_df.rename(columns={'numberofratings':'num_ratings'}, inplace=True)
wine_df

,name,country,region,winery,rating,num_ratings,price,year,lat,lng,...,nov_prcp,nov_tsun,dec_tavg,dec_tmin,dec_tmax,dec_prcp,dec_tsun,type,city,country
0,Pomerol 2011,France,Pomerol,Château La Providence,4.2,100,95.00,2011,44.931123,-0.199990,...,3.606667,16310.877930,3.770352,0.545016,7.278887,2.512903,18816.488281,Red,NaN,NaN
1,Lirac 2017,France,Lirac,Château Mont-Redon,4.3,100,15.50,2017,44.037200,4.691360,...,4.493333,23639.103516,6.816054,2.744145,12.079628,0.961290,25410.091797,Red,NaN,NaN
2,Erta e China Rosso di Toscana 2015,Italy,Toscana,Renzo Masi,3.9,100,7.45,2015,43.458654,11.138920,...,6.703333,16427.396484,7.227470,3.667322,11.165709,1.958065,22149.550781,Red,NaN,NaN
3,Bardolino 2019,Italy,Bardolino,Cavalchina,3.5,100,8.72,2019,45.547559,10.724215,...,2.990000,18802.570312,5.414707,2.268403,8.408726,0.754839,22706.322266,Red,NaN,NaN
4,Ried Scheibner Pinot Noir 2016,Austria,Carnuntum,Markowitsch,3.9,100,29.15,2016,48.114148,16.865783,...,0.703333,21962.705078,3.554911,1.230113,6.362371,0.325806,15976.619141,Red,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13085,Private Bin Sauvignon Blanc 2019,New Zealand,Marlborough,Villa Maria,4.1,4082,10.60,2019,-41.474475,173.833026,...,6.756667,36561.121094,16.466511,12.336403,21.633179,4.058064,38551.261719,White,Marlborough,New Zealand
13086,Blanco (Verdejo) 2018,Spain,Rueda,Marqués de Riscal,3.7,4155,6.30,2018,41.412979,-4.959753,...,0.740000,27725.917969,4.169382,0.314274,8.949759,1.112903,18953.107422,White,Rueda,Spain
13087,Sauvignon Blanc 2019,New Zealand,Marlborough,Oyster Bay,4.0,4423,10.66,2019,-41.474475,173.833026,...,6.756667,36561.121094,16.466511,12.336403,21.633179,4.058064,38551.261719,White,Marlborough,New Zealand
13088,Sauvignon Blanc 2018,New Zealand,Marlborough,Kim Crawford,3.9,5105,14.90,2018,-41.474475,173.833026,...,0.436667,37763.203125,18.173969,12.646081,24.600918,1.719355,44898.128906,White,Marlborough,New Zealand
13089,Sauvignon Blanc 2019,New Zealand,Marlborough,Hans Greyl,4.2,5817,7.75,2019,-41.474475,173.833026,...,6.756667,36561.121094,16.466511,12.336403,21.633179,4.058064,38551.261719,White,Marlborough,New Zealand

In [7]:
duplicates = wine_df[wine_df.duplicated()]
print(duplicates)

Empty DataFrame
Columns: [name, country, region, winery, rating, num_ratings, price, year, lat, lng, jan_tavg, jan_tmin, jan_tmax, jan_prcp, jan_tsun, feb_tavg, feb_tmin, feb_tmax, feb_prcp, feb_tsun, mar_tavg, mar_tmin, mar_tmax, mar_prcp, mar_tsun, apr_tavg, apr_tmin, apr_tmax, apr_prcp, apr_tsun, may_tavg, may_tmin, may_tmax, may_prcp, may_tsun, jun_tavg, jun_tmin, jun_tmax, jun_prcp, jun_tsun, jul_tavg, jul_tmin, jul_tmax, jul_prcp, jul_tsun, aug_tavg, aug_tmin, aug_tmax, aug_prcp, aug_tsun, sep_tavg, sep_tmin, sep_tmax, sep_prcp, sep_tsun, oct_tavg, oct_tmin, oct_tmax, oct_prcp, oct_tsun, nov_tavg, nov_tmin, nov_tmax, nov_prcp, nov_tsun, dec_tavg, dec_tmin, dec_tmax, dec_prcp, dec_tsun, type, city, country]
Index: []

[0 rows x 73 columns]

In [8]:
wine_df.isnull().sum()

name           0
country        0
region         0
winery         0
rating         0
            ...
dec_prcp       0
dec_tsun       0
type           0
city        9331
country     9331
Length: 73, dtype: int64

In [9]:
wine_df.dtypes

name         object
country      object
region       object
winery       object
rating      float64
             ...
dec_prcp    float64
dec_tsun    float64
type         object
city         object
country      object
Length: 73, dtype: object

In [10]:
wine_df.to_csv('wine_weather.csv', index=False)

In [11]:
wine_df2 = pd.read_csv('wine_df2.csv')
climate_df = pd.read_csv('climate_df.csv')
region_df = pd.read_csv('region_df.csv')

In [14]:
wine_df2

,name,winery,year,rating,num_ratings,price,type,region
0,Pomerol 2011,Château La Providence,2011,4.2,100,95.00,Red,Pomerol
1,Lirac 2017,Château Mont-Redon,2017,4.3,100,15.50,Red,Lirac
2,Erta e China Rosso di Toscana 2015,Renzo Masi,2015,3.9,100,7.45,Red,Toscana
3,Bardolino 2019,Cavalchina,2019,3.5,100,8.72,Red,Bardolino
4,Ried Scheibner Pinot Noir 2016,Markowitsch,2016,3.9,100,29.15,Red,Carnuntum
...,...,...,...,...,...,...,...,...
13085,Private Bin Sauvignon Blanc 2019,Villa Maria,2019,4.1,4082,10.60,White,Marlborough
13086,Blanco (Verdejo) 2018,Marqués de Riscal,2018,3.7,4155,6.30,White,Rueda
13087,Sauvignon Blanc 2019,Oyster Bay,2019,4.0,4423,10.66,White,Marlborough
13088,Sauvignon Blanc 2018,Kim Crawford,2018,3.9,5105,14.90,White,Marlborough
13089,Sauvignon Blanc 2019,Hans Greyl,2019,4.2,5817,7.75,White,Marlborough